### ISSUE TITLE
CMS Consistency Check is frozen during some steps

### ISSUE THREAD

**Issue by jhonatanamado** [dmwm/rucio-flux#162]
Seems to be an isolated issue for some sites but CC is frozen (or taking more time than expected) for the following sites in in the step Site Scanner and directory removal
https://cmsweb.cern.ch/rucioconmon/ce/show_rse?rse=T1_US_FNAL_Disk.
https://cmsweb.cern.ch/rucioconmon/ce/show_run?rse=T1_DE_KIT_Disk&run=2023_03_25_13_33
https://cmsweb.cern.ch/rucioconmon/ce/show_run?rse=T1_FR_CCIN2P3_Disk&run=2023_03_25_14_25
Is it possible to create some timeouts for this particular steps?

**Comment by giffels** [comment]
The default timeout for a directory listing operation in dCache is 120s. So, if an `ls` command takes 120s and returns an empty listing afterwards, something went wrong. Unfortunately, there is no error message available and the exit code is 0.

**Comment by jhonatanamado** [comment]
I created the following PR to exclude the affected sites. https://github.com/dmwm/rucio-flux/pull/165

**Comment by jhonatanamado** [comment]
@ivmfnal .Is it possible to stop all the active scans for the sites affected ?

**Comment by giffels** [comment]
Thanks a lot, it seems that we did not have any issues with failing SAM tests last weekend.
